title: Food Spots
baseUrl: https://food-spots.com.au

params:
  author: Carlos Melegrito
  description: A curated list of food spots, as reviewed by one Carlos Melegrito

  social:
    twitter: cjmlgrto

taxonomies:
  tag: tags
  location: locations