title: Food Spots
baseUrl: https://carlos-food-spots.netlify.app

params:
  author: Carlos Melegrito
  description: In which Carlos reviews some food spots

  social:
    twitter: cjmlgrto

taxonomies:
  tag: tags
  location: locations